### PR TITLE
Ipython extension

### PR DESCRIPTION
**Pull request by roee30**
Add an extension for using pprintpp for ipython's output.

### CODE REVIEW

**Comment by wolever** [comment]
Awesome! Thanks! One thing: I don't know what the standard for ipython extensions is, but the `%load_ext pprintpp.ipython` bothers my aesthetics.

Could you add something like this to the top-level `pprintpp` module, so it can be loaded with just `%load_ext pprintpp`?


```python

def load_ipython_extension(ipython):
    from .ipython import load_ipython_extension
    return load_ipython_extension(ipython)
```

And it'd be awesome to have that in the `pp` module too, so `%load_ext pp` works too.

**Comment by roee30** [comment]
No problem! ``pp`` got it for free after I added this to ``pprintpp``

**Comment by wolever** [comment]
Ahh thanks for checking. Could you add the attribution as a comment in the relevant file?

**Comment by wolever** [comment]
Wait, sorry, just saw that you did cite the relevant SO links in the comment.

Is there other attribution you're thinking of?

Otherwise, this looks good - I'll give it a final test then cut a new release :)

**Comment by roee30** [comment]
I don't think an attribution to another source is needed. However, like I said, I do wonder whether the one I added should also appear in the README .

**Comment by wolever** [comment]
Woo! Thanks! I've merge'd this to master and pushed 0.4.0 to PyPI! https://pypi.org/project/pprintpp/

**Pull request merged**
